# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CertificateAuthorityRenew(BaseModel):
    """
    CertificateAuthorityRenew
    """ # noqa: E501
    caref: Optional[StrictStr] = Field(default=None, description="The Certificate Authority to renew.<br>")
    reusekey: Optional[StrictBool] = Field(default=True, description="Reuses the existing private key when renewing the certificate authority.<br>")
    reuseserial: Optional[StrictBool] = Field(default=True, description="Reuses the existing serial number when renewing the certificate authority.<br>")
    strictsecurity: Optional[StrictBool] = Field(default=None, description="Enforces strict security measures when renewing the certificate authority.<br>")
    oldserial: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The old serial number of the Certificate Authority before the renewal.<br>")
    newserial: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The new serial number of the Certificate Authority after the renewal.<br>")
    __properties: ClassVar[List[str]] = ["caref", "reusekey", "reuseserial", "strictsecurity", "oldserial", "newserial"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CertificateAuthorityRenew from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "oldserial",
            "newserial",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if oldserial (nullable) is None
        # and model_fields_set contains the field
        if self.oldserial is None and "oldserial" in self.model_fields_set:
            _dict['oldserial'] = None

        # set to None if newserial (nullable) is None
        # and model_fields_set contains the field
        if self.newserial is None and "newserial" in self.model_fields_set:
            _dict['newserial'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CertificateAuthorityRenew from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "caref": obj.get("caref"),
            "reusekey": obj.get("reusekey") if obj.get("reusekey") is not None else True,
            "reuseserial": obj.get("reuseserial") if obj.get("reuseserial") is not None else True,
            "strictsecurity": obj.get("strictsecurity"),
            "oldserial": obj.get("oldserial"),
            "newserial": obj.get("newserial")
        })
        return _obj


