# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pfsense_api_client.models.firewall_schedule_timerange_inner import FirewallScheduleTimerangeInner
from typing import Optional, Set
from typing_extensions import Self

class FirewallSchedule(BaseModel):
    """
    FirewallSchedule
    """ # noqa: E501
    schedlabel: Optional[StrictStr] = Field(default='67ed0819d095f', description="A unique ID for this schedule used internally by the system.<br>")
    name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The unique name to assign this schedule.<br>")
    descr: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="A description of this schedules purpose.<br>")
    active: Optional[StrictBool] = Field(default=None, description="Displays whether the schedule is currently active or not.<br>")
    timerange: Optional[Annotated[List[FirewallScheduleTimerangeInner], Field(min_length=1, max_length=65535)]] = Field(default=None, description="The date/times this firewall schedule will be active.<br>")
    __properties: ClassVar[List[str]] = ["schedlabel", "name", "descr", "active", "timerange"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FirewallSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "schedlabel",
            "active",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in timerange (list)
        _items = []
        if self.timerange:
            for _item_timerange in self.timerange:
                if _item_timerange:
                    _items.append(_item_timerange.to_dict())
            _dict['timerange'] = _items
        # set to None if schedlabel (nullable) is None
        # and model_fields_set contains the field
        if self.schedlabel is None and "schedlabel" in self.model_fields_set:
            _dict['schedlabel'] = None

        # set to None if active (nullable) is None
        # and model_fields_set contains the field
        if self.active is None and "active" in self.model_fields_set:
            _dict['active'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FirewallSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schedlabel": obj.get("schedlabel") if obj.get("schedlabel") is not None else '67ed0819d095f',
            "name": obj.get("name"),
            "descr": obj.get("descr"),
            "active": obj.get("active"),
            "timerange": [FirewallScheduleTimerangeInner.from_dict(_item) for _item in obj["timerange"]] if obj.get("timerange") is not None else None
        })
        return _obj


