# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class HAProxyBackendAclsInner(BaseModel):
    """
    HAProxyBackendAclsInner
    """ # noqa: E501
    name: Annotated[str, Field(min_length=2, strict=True, max_length=1024)] = Field(description="The unique name for this backend ACL.<br>")
    expression: Annotated[str, Field(min_length=0, strict=True, max_length=1024)] = Field(description="The expression to use to determine the match for this ACL.<br>")
    value: Annotated[str, Field(min_length=0, strict=True, max_length=1024)] = Field(description="The value which indicates a match for this ACL.<br>")
    casesensitive: Optional[StrictBool] = Field(default=None, description="Enables or disables case-sensitive matching for this ACL.<br>")
    var_not: Optional[StrictBool] = Field(default=None, description="Enables or disables inverting the context of this ACL.<br>", alias="not")
    __properties: ClassVar[List[str]] = ["name", "expression", "value", "casesensitive", "not"]

    @field_validator('expression')
    def expression_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['host_starts_with', 'host_ends_with', 'host_matches', 'host_regex', 'host_contains', 'path_starts_with', 'path_ends_with', 'path_matches', 'path_regex', 'path_contains', 'path_dir', 'url_parameter', 'ssl_c_verify_code', 'ssl_c_verify', 'ssl_c_ca_commonname', 'source_ip', 'backendservercount', 'traffic_is_http', 'traffic_is_ssl', 'ssl_sni_matches', 'ssl_sni_contains', 'ssl_sni_starts_with', 'ssl_sni_ends_with', 'ssl_sni_regex', 'custom']):
            raise ValueError("must be one of enum values ('host_starts_with', 'host_ends_with', 'host_matches', 'host_regex', 'host_contains', 'path_starts_with', 'path_ends_with', 'path_matches', 'path_regex', 'path_contains', 'path_dir', 'url_parameter', 'ssl_c_verify_code', 'ssl_c_verify', 'ssl_c_ca_commonname', 'source_ip', 'backendservercount', 'traffic_is_http', 'traffic_is_ssl', 'ssl_sni_matches', 'ssl_sni_contains', 'ssl_sni_starts_with', 'ssl_sni_ends_with', 'ssl_sni_regex', 'custom')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HAProxyBackendAclsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HAProxyBackendAclsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "expression": obj.get("expression"),
            "value": obj.get("value"),
            "casesensitive": obj.get("casesensitive"),
            "not": obj.get("not")
        })
        return _obj


