# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class OpenVPNClientStatus(BaseModel):
    """
    OpenVPNClientStatus
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The name of the OpenVPN client.<br>")
    port: Optional[StrictStr] = Field(default=None, description="The port number of the OpenVPN client. Valid options are: a TCP/UDP port number<br>")
    vpnid: Optional[StrictInt] = Field(default=None, description="The VPN ID of the OpenVPN client this status corresponds to.<br>")
    mgmt: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The management interface of the OpenVPN client.<br>")
    status: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The current status of the OpenVPN client.<br>")
    state: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The current state of the OpenVPN client.<br>")
    state_detail: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The details for the current state of the OpenVPN client.<br>")
    connect_time: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The connection time of the OpenVPN client.<br>")
    virtual_addr: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The virtual address of the OpenVPN client.<br>")
    virtual_addr6: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The virtual address 6 of the OpenVPN client.<br>")
    remote_host: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The remote host of the OpenVPN client.<br>")
    remote_port: Optional[StrictStr] = Field(default=None, description="The remote port of the OpenVPN client. Valid options are: a TCP/UDP port number<br>")
    local_host: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The local host of the OpenVPN client.<br>")
    local_port: Optional[StrictStr] = Field(default=None, description="The local port of the OpenVPN client. Valid options are: a TCP/UDP port number<br>")
    __properties: ClassVar[List[str]] = ["name", "port", "vpnid", "mgmt", "status", "state", "state_detail", "connect_time", "virtual_addr", "virtual_addr6", "remote_host", "remote_port", "local_host", "local_port"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenVPNClientStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "name",
            "port",
            "vpnid",
            "mgmt",
            "status",
            "state",
            "state_detail",
            "connect_time",
            "virtual_addr",
            "virtual_addr6",
            "remote_host",
            "remote_port",
            "local_host",
            "local_port",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if port (nullable) is None
        # and model_fields_set contains the field
        if self.port is None and "port" in self.model_fields_set:
            _dict['port'] = None

        # set to None if vpnid (nullable) is None
        # and model_fields_set contains the field
        if self.vpnid is None and "vpnid" in self.model_fields_set:
            _dict['vpnid'] = None

        # set to None if mgmt (nullable) is None
        # and model_fields_set contains the field
        if self.mgmt is None and "mgmt" in self.model_fields_set:
            _dict['mgmt'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if state_detail (nullable) is None
        # and model_fields_set contains the field
        if self.state_detail is None and "state_detail" in self.model_fields_set:
            _dict['state_detail'] = None

        # set to None if connect_time (nullable) is None
        # and model_fields_set contains the field
        if self.connect_time is None and "connect_time" in self.model_fields_set:
            _dict['connect_time'] = None

        # set to None if virtual_addr (nullable) is None
        # and model_fields_set contains the field
        if self.virtual_addr is None and "virtual_addr" in self.model_fields_set:
            _dict['virtual_addr'] = None

        # set to None if virtual_addr6 (nullable) is None
        # and model_fields_set contains the field
        if self.virtual_addr6 is None and "virtual_addr6" in self.model_fields_set:
            _dict['virtual_addr6'] = None

        # set to None if remote_host (nullable) is None
        # and model_fields_set contains the field
        if self.remote_host is None and "remote_host" in self.model_fields_set:
            _dict['remote_host'] = None

        # set to None if remote_port (nullable) is None
        # and model_fields_set contains the field
        if self.remote_port is None and "remote_port" in self.model_fields_set:
            _dict['remote_port'] = None

        # set to None if local_host (nullable) is None
        # and model_fields_set contains the field
        if self.local_host is None and "local_host" in self.model_fields_set:
            _dict['local_host'] = None

        # set to None if local_port (nullable) is None
        # and model_fields_set contains the field
        if self.local_port is None and "local_port" in self.model_fields_set:
            _dict['local_port'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenVPNClientStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "port": obj.get("port"),
            "vpnid": obj.get("vpnid"),
            "mgmt": obj.get("mgmt"),
            "status": obj.get("status"),
            "state": obj.get("state"),
            "state_detail": obj.get("state_detail"),
            "connect_time": obj.get("connect_time"),
            "virtual_addr": obj.get("virtual_addr"),
            "virtual_addr6": obj.get("virtual_addr6"),
            "remote_host": obj.get("remote_host"),
            "remote_port": obj.get("remote_port"),
            "local_host": obj.get("local_host"),
            "local_port": obj.get("local_port")
        })
        return _obj


