# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RESTAPIVersion(BaseModel):
    """
    RESTAPIVersion
    """ # noqa: E501
    current_version: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The current API version installed on this system.<br>")
    latest_version: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The latest API version available to this system.<br>")
    latest_version_release_date: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="The latest API version's release date.<br>")
    update_available: Optional[StrictBool] = Field(default=None, description="Indicates if an API update is available for this system.<br>")
    install_version: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]] = Field(default=None, description="Set the API version to update or rollback to.<br>")
    available_versions: Optional[Annotated[List[Annotated[str, Field(min_length=0, strict=True, max_length=1024)]], Field(min_length=0, max_length=128)]] = Field(default=None, description="All available versions of the REST API package for this system.<br>")
    __properties: ClassVar[List[str]] = ["current_version", "latest_version", "latest_version_release_date", "update_available", "install_version", "available_versions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RESTAPIVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "current_version",
            "latest_version",
            "latest_version_release_date",
            "update_available",
            "available_versions",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if current_version (nullable) is None
        # and model_fields_set contains the field
        if self.current_version is None and "current_version" in self.model_fields_set:
            _dict['current_version'] = None

        # set to None if latest_version (nullable) is None
        # and model_fields_set contains the field
        if self.latest_version is None and "latest_version" in self.model_fields_set:
            _dict['latest_version'] = None

        # set to None if latest_version_release_date (nullable) is None
        # and model_fields_set contains the field
        if self.latest_version_release_date is None and "latest_version_release_date" in self.model_fields_set:
            _dict['latest_version_release_date'] = None

        # set to None if update_available (nullable) is None
        # and model_fields_set contains the field
        if self.update_available is None and "update_available" in self.model_fields_set:
            _dict['update_available'] = None

        # set to None if install_version (nullable) is None
        # and model_fields_set contains the field
        if self.install_version is None and "install_version" in self.model_fields_set:
            _dict['install_version'] = None

        # set to None if available_versions (nullable) is None
        # and model_fields_set contains the field
        if self.available_versions is None and "available_versions" in self.model_fields_set:
            _dict['available_versions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RESTAPIVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "current_version": obj.get("current_version"),
            "latest_version": obj.get("latest_version"),
            "latest_version_release_date": obj.get("latest_version_release_date"),
            "update_available": obj.get("update_available"),
            "install_version": obj.get("install_version"),
            "available_versions": obj.get("available_versions")
        })
        return _obj


