# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfsense_api_client.api.services_api import SERVICESApi


class TestSERVICESApi(unittest.TestCase):
    """SERVICESApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SERVICESApi()

    def tearDown(self) -> None:
        pass

    def test_delete_services_acme_account_key_endpoint(self) -> None:
        """Test case for delete_services_acme_account_key_endpoint

        """
        pass

    def test_delete_services_acme_account_keys_endpoint(self) -> None:
        """Test case for delete_services_acme_account_keys_endpoint

        """
        pass

    def test_delete_services_acme_certificate_action_endpoint(self) -> None:
        """Test case for delete_services_acme_certificate_action_endpoint

        """
        pass

    def test_delete_services_acme_certificate_domain_endpoint(self) -> None:
        """Test case for delete_services_acme_certificate_domain_endpoint

        """
        pass

    def test_delete_services_acme_certificate_endpoint(self) -> None:
        """Test case for delete_services_acme_certificate_endpoint

        """
        pass

    def test_delete_services_acme_certificates_endpoint(self) -> None:
        """Test case for delete_services_acme_certificates_endpoint

        """
        pass

    def test_delete_services_bind_access_list_endpoint(self) -> None:
        """Test case for delete_services_bind_access_list_endpoint

        """
        pass

    def test_delete_services_bind_access_list_entry_endpoint(self) -> None:
        """Test case for delete_services_bind_access_list_entry_endpoint

        """
        pass

    def test_delete_services_bind_access_lists_endpoint(self) -> None:
        """Test case for delete_services_bind_access_lists_endpoint

        """
        pass

    def test_delete_services_bind_sync_remote_host_endpoint(self) -> None:
        """Test case for delete_services_bind_sync_remote_host_endpoint

        """
        pass

    def test_delete_services_bind_sync_remote_hosts_endpoint(self) -> None:
        """Test case for delete_services_bind_sync_remote_hosts_endpoint

        """
        pass

    def test_delete_services_bind_view_endpoint(self) -> None:
        """Test case for delete_services_bind_view_endpoint

        """
        pass

    def test_delete_services_bind_views_endpoint(self) -> None:
        """Test case for delete_services_bind_views_endpoint

        """
        pass

    def test_delete_services_bind_zone_endpoint(self) -> None:
        """Test case for delete_services_bind_zone_endpoint

        """
        pass

    def test_delete_services_bind_zone_record_endpoint(self) -> None:
        """Test case for delete_services_bind_zone_record_endpoint

        """
        pass

    def test_delete_services_bind_zones_endpoint(self) -> None:
        """Test case for delete_services_bind_zones_endpoint

        """
        pass

    def test_delete_services_cron_job_endpoint(self) -> None:
        """Test case for delete_services_cron_job_endpoint

        """
        pass

    def test_delete_services_cron_jobs_endpoint(self) -> None:
        """Test case for delete_services_cron_jobs_endpoint

        """
        pass

    def test_delete_services_dhcp_server_address_pool_endpoint(self) -> None:
        """Test case for delete_services_dhcp_server_address_pool_endpoint

        """
        pass

    def test_delete_services_dhcp_server_custom_option_endpoint(self) -> None:
        """Test case for delete_services_dhcp_server_custom_option_endpoint

        """
        pass

    def test_delete_services_dhcp_server_static_mapping_endpoint(self) -> None:
        """Test case for delete_services_dhcp_server_static_mapping_endpoint

        """
        pass

    def test_delete_services_dns_forwarder_host_override_alias_endpoint(self) -> None:
        """Test case for delete_services_dns_forwarder_host_override_alias_endpoint

        """
        pass

    def test_delete_services_dns_forwarder_host_override_endpoint(self) -> None:
        """Test case for delete_services_dns_forwarder_host_override_endpoint

        """
        pass

    def test_delete_services_dns_forwarder_host_overrides_endpoint(self) -> None:
        """Test case for delete_services_dns_forwarder_host_overrides_endpoint

        """
        pass

    def test_delete_services_dns_resolver_access_list_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_access_list_endpoint

        """
        pass

    def test_delete_services_dns_resolver_access_list_network_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_access_list_network_endpoint

        """
        pass

    def test_delete_services_dns_resolver_access_lists_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_access_lists_endpoint

        """
        pass

    def test_delete_services_dns_resolver_domain_override_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_domain_override_endpoint

        """
        pass

    def test_delete_services_dns_resolver_domain_overrides_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_domain_overrides_endpoint

        """
        pass

    def test_delete_services_dns_resolver_host_override_alias_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_host_override_alias_endpoint

        """
        pass

    def test_delete_services_dns_resolver_host_override_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_host_override_endpoint

        """
        pass

    def test_delete_services_dns_resolver_host_overrides_endpoint(self) -> None:
        """Test case for delete_services_dns_resolver_host_overrides_endpoint

        """
        pass

    def test_delete_services_ha_proxy_backend_acl_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_backend_acl_endpoint

        """
        pass

    def test_delete_services_ha_proxy_backend_action_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_backend_action_endpoint

        """
        pass

    def test_delete_services_ha_proxy_backend_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_backend_endpoint

        """
        pass

    def test_delete_services_ha_proxy_backend_error_file_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_backend_error_file_endpoint

        """
        pass

    def test_delete_services_ha_proxy_backend_server_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_backend_server_endpoint

        """
        pass

    def test_delete_services_ha_proxy_backends_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_backends_endpoint

        """
        pass

    def test_delete_services_ha_proxy_file_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_file_endpoint

        """
        pass

    def test_delete_services_ha_proxy_files(self) -> None:
        """Test case for delete_services_ha_proxy_files

        """
        pass

    def test_delete_services_ha_proxy_frontend_acl_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_frontend_acl_endpoint

        """
        pass

    def test_delete_services_ha_proxy_frontend_action_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_frontend_action_endpoint

        """
        pass

    def test_delete_services_ha_proxy_frontend_address_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_frontend_address_endpoint

        """
        pass

    def test_delete_services_ha_proxy_frontend_certificate_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_frontend_certificate_endpoint

        """
        pass

    def test_delete_services_ha_proxy_frontend_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_frontend_endpoint

        """
        pass

    def test_delete_services_ha_proxy_frontend_error_file_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_frontend_error_file_endpoint

        """
        pass

    def test_delete_services_ha_proxy_frontends_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_frontends_endpoint

        """
        pass

    def test_delete_services_ha_proxy_settings_dns_resolver_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_settings_dns_resolver_endpoint

        """
        pass

    def test_delete_services_ha_proxy_settings_email_mailer_endpoint(self) -> None:
        """Test case for delete_services_ha_proxy_settings_email_mailer_endpoint

        """
        pass

    def test_delete_services_ntp_time_server_endpoint(self) -> None:
        """Test case for delete_services_ntp_time_server_endpoint

        """
        pass

    def test_delete_services_ntp_time_servers_endpoint(self) -> None:
        """Test case for delete_services_ntp_time_servers_endpoint

        """
        pass

    def test_delete_services_service_watchdog_endpoint(self) -> None:
        """Test case for delete_services_service_watchdog_endpoint

        """
        pass

    def test_delete_services_service_watchdogs_endpoint(self) -> None:
        """Test case for delete_services_service_watchdogs_endpoint

        """
        pass

    def test_get_services_acme_account_key_endpoint(self) -> None:
        """Test case for get_services_acme_account_key_endpoint

        """
        pass

    def test_get_services_acme_account_key_registrations_endpoint(self) -> None:
        """Test case for get_services_acme_account_key_registrations_endpoint

        """
        pass

    def test_get_services_acme_account_keys_endpoint(self) -> None:
        """Test case for get_services_acme_account_keys_endpoint

        """
        pass

    def test_get_services_acme_certificate_action_endpoint(self) -> None:
        """Test case for get_services_acme_certificate_action_endpoint

        """
        pass

    def test_get_services_acme_certificate_domain_endpoint(self) -> None:
        """Test case for get_services_acme_certificate_domain_endpoint

        """
        pass

    def test_get_services_acme_certificate_endpoint(self) -> None:
        """Test case for get_services_acme_certificate_endpoint

        """
        pass

    def test_get_services_acme_certificate_issuances_endpoint(self) -> None:
        """Test case for get_services_acme_certificate_issuances_endpoint

        """
        pass

    def test_get_services_acme_certificate_renewals_endpoint(self) -> None:
        """Test case for get_services_acme_certificate_renewals_endpoint

        """
        pass

    def test_get_services_acme_certificates_endpoint(self) -> None:
        """Test case for get_services_acme_certificates_endpoint

        """
        pass

    def test_get_services_acme_settings_endpoint(self) -> None:
        """Test case for get_services_acme_settings_endpoint

        """
        pass

    def test_get_services_bind_access_list_endpoint(self) -> None:
        """Test case for get_services_bind_access_list_endpoint

        """
        pass

    def test_get_services_bind_access_list_entry_endpoint(self) -> None:
        """Test case for get_services_bind_access_list_entry_endpoint

        """
        pass

    def test_get_services_bind_access_lists_endpoint(self) -> None:
        """Test case for get_services_bind_access_lists_endpoint

        """
        pass

    def test_get_services_bind_settings_endpoint(self) -> None:
        """Test case for get_services_bind_settings_endpoint

        """
        pass

    def test_get_services_bind_sync_remote_host_endpoint(self) -> None:
        """Test case for get_services_bind_sync_remote_host_endpoint

        """
        pass

    def test_get_services_bind_sync_remote_hosts_endpoint(self) -> None:
        """Test case for get_services_bind_sync_remote_hosts_endpoint

        """
        pass

    def test_get_services_bind_sync_settings_endpoint(self) -> None:
        """Test case for get_services_bind_sync_settings_endpoint

        """
        pass

    def test_get_services_bind_view_endpoint(self) -> None:
        """Test case for get_services_bind_view_endpoint

        """
        pass

    def test_get_services_bind_views_endpoint(self) -> None:
        """Test case for get_services_bind_views_endpoint

        """
        pass

    def test_get_services_bind_zone_endpoint(self) -> None:
        """Test case for get_services_bind_zone_endpoint

        """
        pass

    def test_get_services_bind_zone_record_endpoint(self) -> None:
        """Test case for get_services_bind_zone_record_endpoint

        """
        pass

    def test_get_services_bind_zones_endpoint(self) -> None:
        """Test case for get_services_bind_zones_endpoint

        """
        pass

    def test_get_services_cron_job_endpoint(self) -> None:
        """Test case for get_services_cron_job_endpoint

        """
        pass

    def test_get_services_cron_jobs_endpoint(self) -> None:
        """Test case for get_services_cron_jobs_endpoint

        """
        pass

    def test_get_services_dhcp_relay_endpoint(self) -> None:
        """Test case for get_services_dhcp_relay_endpoint

        """
        pass

    def test_get_services_dhcp_server_address_pool_endpoint(self) -> None:
        """Test case for get_services_dhcp_server_address_pool_endpoint

        """
        pass

    def test_get_services_dhcp_server_apply_endpoint(self) -> None:
        """Test case for get_services_dhcp_server_apply_endpoint

        """
        pass

    def test_get_services_dhcp_server_custom_option_endpoint(self) -> None:
        """Test case for get_services_dhcp_server_custom_option_endpoint

        """
        pass

    def test_get_services_dhcp_server_endpoint(self) -> None:
        """Test case for get_services_dhcp_server_endpoint

        """
        pass

    def test_get_services_dhcp_server_static_mapping_endpoint(self) -> None:
        """Test case for get_services_dhcp_server_static_mapping_endpoint

        """
        pass

    def test_get_services_dhcp_servers_endpoint(self) -> None:
        """Test case for get_services_dhcp_servers_endpoint

        """
        pass

    def test_get_services_dns_forwarder_apply_endpoint(self) -> None:
        """Test case for get_services_dns_forwarder_apply_endpoint

        """
        pass

    def test_get_services_dns_forwarder_host_override_alias_endpoint(self) -> None:
        """Test case for get_services_dns_forwarder_host_override_alias_endpoint

        """
        pass

    def test_get_services_dns_forwarder_host_override_endpoint(self) -> None:
        """Test case for get_services_dns_forwarder_host_override_endpoint

        """
        pass

    def test_get_services_dns_forwarder_host_overrides_endpoint(self) -> None:
        """Test case for get_services_dns_forwarder_host_overrides_endpoint

        """
        pass

    def test_get_services_dns_resolver_access_list_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_access_list_endpoint

        """
        pass

    def test_get_services_dns_resolver_access_list_network_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_access_list_network_endpoint

        """
        pass

    def test_get_services_dns_resolver_access_lists_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_access_lists_endpoint

        """
        pass

    def test_get_services_dns_resolver_apply_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_apply_endpoint

        """
        pass

    def test_get_services_dns_resolver_domain_override_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_domain_override_endpoint

        """
        pass

    def test_get_services_dns_resolver_domain_overrides_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_domain_overrides_endpoint

        """
        pass

    def test_get_services_dns_resolver_host_override_alias_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_host_override_alias_endpoint

        """
        pass

    def test_get_services_dns_resolver_host_override_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_host_override_endpoint

        """
        pass

    def test_get_services_dns_resolver_host_overrides_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_host_overrides_endpoint

        """
        pass

    def test_get_services_dns_resolver_settings_endpoint(self) -> None:
        """Test case for get_services_dns_resolver_settings_endpoint

        """
        pass

    def test_get_services_ha_proxy_apply_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_apply_endpoint

        """
        pass

    def test_get_services_ha_proxy_backend_acl_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_backend_acl_endpoint

        """
        pass

    def test_get_services_ha_proxy_backend_action_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_backend_action_endpoint

        """
        pass

    def test_get_services_ha_proxy_backend_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_backend_endpoint

        """
        pass

    def test_get_services_ha_proxy_backend_error_file_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_backend_error_file_endpoint

        """
        pass

    def test_get_services_ha_proxy_backend_server_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_backend_server_endpoint

        """
        pass

    def test_get_services_ha_proxy_backends_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_backends_endpoint

        """
        pass

    def test_get_services_ha_proxy_file_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_file_endpoint

        """
        pass

    def test_get_services_ha_proxy_files(self) -> None:
        """Test case for get_services_ha_proxy_files

        """
        pass

    def test_get_services_ha_proxy_frontend_acl_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_frontend_acl_endpoint

        """
        pass

    def test_get_services_ha_proxy_frontend_action_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_frontend_action_endpoint

        """
        pass

    def test_get_services_ha_proxy_frontend_address_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_frontend_address_endpoint

        """
        pass

    def test_get_services_ha_proxy_frontend_certificate_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_frontend_certificate_endpoint

        """
        pass

    def test_get_services_ha_proxy_frontend_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_frontend_endpoint

        """
        pass

    def test_get_services_ha_proxy_frontend_error_file_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_frontend_error_file_endpoint

        """
        pass

    def test_get_services_ha_proxy_frontends_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_frontends_endpoint

        """
        pass

    def test_get_services_ha_proxy_settings_dns_resolver_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_settings_dns_resolver_endpoint

        """
        pass

    def test_get_services_ha_proxy_settings_email_mailer_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_settings_email_mailer_endpoint

        """
        pass

    def test_get_services_ha_proxy_settings_endpoint(self) -> None:
        """Test case for get_services_ha_proxy_settings_endpoint

        """
        pass

    def test_get_services_ntp_settings_endpoint(self) -> None:
        """Test case for get_services_ntp_settings_endpoint

        """
        pass

    def test_get_services_ntp_time_server_endpoint(self) -> None:
        """Test case for get_services_ntp_time_server_endpoint

        """
        pass

    def test_get_services_ntp_time_servers_endpoint(self) -> None:
        """Test case for get_services_ntp_time_servers_endpoint

        """
        pass

    def test_get_services_service_watchdog_endpoint(self) -> None:
        """Test case for get_services_service_watchdog_endpoint

        """
        pass

    def test_get_services_service_watchdogs_endpoint(self) -> None:
        """Test case for get_services_service_watchdogs_endpoint

        """
        pass

    def test_get_services_ssh_endpoint(self) -> None:
        """Test case for get_services_ssh_endpoint

        """
        pass

    def test_patch_services_acme_account_key_endpoint(self) -> None:
        """Test case for patch_services_acme_account_key_endpoint

        """
        pass

    def test_patch_services_acme_certificate_action_endpoint(self) -> None:
        """Test case for patch_services_acme_certificate_action_endpoint

        """
        pass

    def test_patch_services_acme_certificate_domain_endpoint(self) -> None:
        """Test case for patch_services_acme_certificate_domain_endpoint

        """
        pass

    def test_patch_services_acme_certificate_endpoint(self) -> None:
        """Test case for patch_services_acme_certificate_endpoint

        """
        pass

    def test_patch_services_acme_settings_endpoint(self) -> None:
        """Test case for patch_services_acme_settings_endpoint

        """
        pass

    def test_patch_services_bind_access_list_endpoint(self) -> None:
        """Test case for patch_services_bind_access_list_endpoint

        """
        pass

    def test_patch_services_bind_access_list_entry_endpoint(self) -> None:
        """Test case for patch_services_bind_access_list_entry_endpoint

        """
        pass

    def test_patch_services_bind_settings_endpoint(self) -> None:
        """Test case for patch_services_bind_settings_endpoint

        """
        pass

    def test_patch_services_bind_sync_remote_host_endpoint(self) -> None:
        """Test case for patch_services_bind_sync_remote_host_endpoint

        """
        pass

    def test_patch_services_bind_sync_settings_endpoint(self) -> None:
        """Test case for patch_services_bind_sync_settings_endpoint

        """
        pass

    def test_patch_services_bind_view_endpoint(self) -> None:
        """Test case for patch_services_bind_view_endpoint

        """
        pass

    def test_patch_services_bind_zone_endpoint(self) -> None:
        """Test case for patch_services_bind_zone_endpoint

        """
        pass

    def test_patch_services_bind_zone_record_endpoint(self) -> None:
        """Test case for patch_services_bind_zone_record_endpoint

        """
        pass

    def test_patch_services_cron_job_endpoint(self) -> None:
        """Test case for patch_services_cron_job_endpoint

        """
        pass

    def test_patch_services_dhcp_relay_endpoint(self) -> None:
        """Test case for patch_services_dhcp_relay_endpoint

        """
        pass

    def test_patch_services_dhcp_server_address_pool_endpoint(self) -> None:
        """Test case for patch_services_dhcp_server_address_pool_endpoint

        """
        pass

    def test_patch_services_dhcp_server_backend_endpoint(self) -> None:
        """Test case for patch_services_dhcp_server_backend_endpoint

        """
        pass

    def test_patch_services_dhcp_server_custom_option_endpoint(self) -> None:
        """Test case for patch_services_dhcp_server_custom_option_endpoint

        """
        pass

    def test_patch_services_dhcp_server_endpoint(self) -> None:
        """Test case for patch_services_dhcp_server_endpoint

        """
        pass

    def test_patch_services_dhcp_server_static_mapping_endpoint(self) -> None:
        """Test case for patch_services_dhcp_server_static_mapping_endpoint

        """
        pass

    def test_patch_services_dns_forwarder_host_override_alias_endpoint(self) -> None:
        """Test case for patch_services_dns_forwarder_host_override_alias_endpoint

        """
        pass

    def test_patch_services_dns_forwarder_host_override_endpoint(self) -> None:
        """Test case for patch_services_dns_forwarder_host_override_endpoint

        """
        pass

    def test_patch_services_dns_resolver_access_list_endpoint(self) -> None:
        """Test case for patch_services_dns_resolver_access_list_endpoint

        """
        pass

    def test_patch_services_dns_resolver_access_list_network_endpoint(self) -> None:
        """Test case for patch_services_dns_resolver_access_list_network_endpoint

        """
        pass

    def test_patch_services_dns_resolver_domain_override_endpoint(self) -> None:
        """Test case for patch_services_dns_resolver_domain_override_endpoint

        """
        pass

    def test_patch_services_dns_resolver_host_override_alias_endpoint(self) -> None:
        """Test case for patch_services_dns_resolver_host_override_alias_endpoint

        """
        pass

    def test_patch_services_dns_resolver_host_override_endpoint(self) -> None:
        """Test case for patch_services_dns_resolver_host_override_endpoint

        """
        pass

    def test_patch_services_dns_resolver_settings_endpoint(self) -> None:
        """Test case for patch_services_dns_resolver_settings_endpoint

        """
        pass

    def test_patch_services_ha_proxy_backend_acl_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_backend_acl_endpoint

        """
        pass

    def test_patch_services_ha_proxy_backend_action_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_backend_action_endpoint

        """
        pass

    def test_patch_services_ha_proxy_backend_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_backend_endpoint

        """
        pass

    def test_patch_services_ha_proxy_backend_error_file_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_backend_error_file_endpoint

        """
        pass

    def test_patch_services_ha_proxy_backend_server_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_backend_server_endpoint

        """
        pass

    def test_patch_services_ha_proxy_file_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_file_endpoint

        """
        pass

    def test_patch_services_ha_proxy_frontend_acl_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_frontend_acl_endpoint

        """
        pass

    def test_patch_services_ha_proxy_frontend_action_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_frontend_action_endpoint

        """
        pass

    def test_patch_services_ha_proxy_frontend_address_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_frontend_address_endpoint

        """
        pass

    def test_patch_services_ha_proxy_frontend_certificate_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_frontend_certificate_endpoint

        """
        pass

    def test_patch_services_ha_proxy_frontend_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_frontend_endpoint

        """
        pass

    def test_patch_services_ha_proxy_frontend_error_file_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_frontend_error_file_endpoint

        """
        pass

    def test_patch_services_ha_proxy_settings_dns_resolver_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_settings_dns_resolver_endpoint

        """
        pass

    def test_patch_services_ha_proxy_settings_email_mailer_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_settings_email_mailer_endpoint

        """
        pass

    def test_patch_services_ha_proxy_settings_endpoint(self) -> None:
        """Test case for patch_services_ha_proxy_settings_endpoint

        """
        pass

    def test_patch_services_ntp_settings_endpoint(self) -> None:
        """Test case for patch_services_ntp_settings_endpoint

        """
        pass

    def test_patch_services_ntp_time_server_endpoint(self) -> None:
        """Test case for patch_services_ntp_time_server_endpoint

        """
        pass

    def test_patch_services_service_watchdog_endpoint(self) -> None:
        """Test case for patch_services_service_watchdog_endpoint

        """
        pass

    def test_patch_services_ssh_endpoint(self) -> None:
        """Test case for patch_services_ssh_endpoint

        """
        pass

    def test_post_services_acme_account_key_endpoint(self) -> None:
        """Test case for post_services_acme_account_key_endpoint

        """
        pass

    def test_post_services_acme_account_key_register_endpoint(self) -> None:
        """Test case for post_services_acme_account_key_register_endpoint

        """
        pass

    def test_post_services_acme_certificate_action_endpoint(self) -> None:
        """Test case for post_services_acme_certificate_action_endpoint

        """
        pass

    def test_post_services_acme_certificate_domain_endpoint(self) -> None:
        """Test case for post_services_acme_certificate_domain_endpoint

        """
        pass

    def test_post_services_acme_certificate_endpoint(self) -> None:
        """Test case for post_services_acme_certificate_endpoint

        """
        pass

    def test_post_services_acme_certificate_issue_endpoint(self) -> None:
        """Test case for post_services_acme_certificate_issue_endpoint

        """
        pass

    def test_post_services_acme_certificate_renew_endpoint(self) -> None:
        """Test case for post_services_acme_certificate_renew_endpoint

        """
        pass

    def test_post_services_bind_access_list_endpoint(self) -> None:
        """Test case for post_services_bind_access_list_endpoint

        """
        pass

    def test_post_services_bind_access_list_entry_endpoint(self) -> None:
        """Test case for post_services_bind_access_list_entry_endpoint

        """
        pass

    def test_post_services_bind_sync_remote_host_endpoint(self) -> None:
        """Test case for post_services_bind_sync_remote_host_endpoint

        """
        pass

    def test_post_services_bind_view_endpoint(self) -> None:
        """Test case for post_services_bind_view_endpoint

        """
        pass

    def test_post_services_bind_zone_endpoint(self) -> None:
        """Test case for post_services_bind_zone_endpoint

        """
        pass

    def test_post_services_bind_zone_record_endpoint(self) -> None:
        """Test case for post_services_bind_zone_record_endpoint

        """
        pass

    def test_post_services_cron_job_endpoint(self) -> None:
        """Test case for post_services_cron_job_endpoint

        """
        pass

    def test_post_services_dhcp_server_address_pool_endpoint(self) -> None:
        """Test case for post_services_dhcp_server_address_pool_endpoint

        """
        pass

    def test_post_services_dhcp_server_apply_endpoint(self) -> None:
        """Test case for post_services_dhcp_server_apply_endpoint

        """
        pass

    def test_post_services_dhcp_server_custom_option_endpoint(self) -> None:
        """Test case for post_services_dhcp_server_custom_option_endpoint

        """
        pass

    def test_post_services_dhcp_server_static_mapping_endpoint(self) -> None:
        """Test case for post_services_dhcp_server_static_mapping_endpoint

        """
        pass

    def test_post_services_dns_forwarder_apply_endpoint(self) -> None:
        """Test case for post_services_dns_forwarder_apply_endpoint

        """
        pass

    def test_post_services_dns_forwarder_host_override_alias_endpoint(self) -> None:
        """Test case for post_services_dns_forwarder_host_override_alias_endpoint

        """
        pass

    def test_post_services_dns_forwarder_host_override_endpoint(self) -> None:
        """Test case for post_services_dns_forwarder_host_override_endpoint

        """
        pass

    def test_post_services_dns_resolver_access_list_endpoint(self) -> None:
        """Test case for post_services_dns_resolver_access_list_endpoint

        """
        pass

    def test_post_services_dns_resolver_access_list_network_endpoint(self) -> None:
        """Test case for post_services_dns_resolver_access_list_network_endpoint

        """
        pass

    def test_post_services_dns_resolver_apply_endpoint(self) -> None:
        """Test case for post_services_dns_resolver_apply_endpoint

        """
        pass

    def test_post_services_dns_resolver_domain_override_endpoint(self) -> None:
        """Test case for post_services_dns_resolver_domain_override_endpoint

        """
        pass

    def test_post_services_dns_resolver_host_override_alias_endpoint(self) -> None:
        """Test case for post_services_dns_resolver_host_override_alias_endpoint

        """
        pass

    def test_post_services_dns_resolver_host_override_endpoint(self) -> None:
        """Test case for post_services_dns_resolver_host_override_endpoint

        """
        pass

    def test_post_services_ha_proxy_apply_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_apply_endpoint

        """
        pass

    def test_post_services_ha_proxy_backend_acl_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_backend_acl_endpoint

        """
        pass

    def test_post_services_ha_proxy_backend_action_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_backend_action_endpoint

        """
        pass

    def test_post_services_ha_proxy_backend_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_backend_endpoint

        """
        pass

    def test_post_services_ha_proxy_backend_error_file_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_backend_error_file_endpoint

        """
        pass

    def test_post_services_ha_proxy_backend_server_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_backend_server_endpoint

        """
        pass

    def test_post_services_ha_proxy_file_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_file_endpoint

        """
        pass

    def test_post_services_ha_proxy_frontend_acl_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_frontend_acl_endpoint

        """
        pass

    def test_post_services_ha_proxy_frontend_action_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_frontend_action_endpoint

        """
        pass

    def test_post_services_ha_proxy_frontend_address_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_frontend_address_endpoint

        """
        pass

    def test_post_services_ha_proxy_frontend_certificate_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_frontend_certificate_endpoint

        """
        pass

    def test_post_services_ha_proxy_frontend_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_frontend_endpoint

        """
        pass

    def test_post_services_ha_proxy_frontend_error_file_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_frontend_error_file_endpoint

        """
        pass

    def test_post_services_ha_proxy_settings_dns_resolver_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_settings_dns_resolver_endpoint

        """
        pass

    def test_post_services_ha_proxy_settings_email_mailer_endpoint(self) -> None:
        """Test case for post_services_ha_proxy_settings_email_mailer_endpoint

        """
        pass

    def test_post_services_ntp_time_server_endpoint(self) -> None:
        """Test case for post_services_ntp_time_server_endpoint

        """
        pass

    def test_post_services_service_watchdog_endpoint(self) -> None:
        """Test case for post_services_service_watchdog_endpoint

        """
        pass

    def test_post_services_wake_on_lan_send_endpoint(self) -> None:
        """Test case for post_services_wake_on_lan_send_endpoint

        """
        pass

    def test_put_services_acme_account_keys_endpoint(self) -> None:
        """Test case for put_services_acme_account_keys_endpoint

        """
        pass

    def test_put_services_acme_certificates_endpoint(self) -> None:
        """Test case for put_services_acme_certificates_endpoint

        """
        pass

    def test_put_services_bind_access_lists_endpoint(self) -> None:
        """Test case for put_services_bind_access_lists_endpoint

        """
        pass

    def test_put_services_bind_sync_remote_hosts_endpoint(self) -> None:
        """Test case for put_services_bind_sync_remote_hosts_endpoint

        """
        pass

    def test_put_services_bind_views_endpoint(self) -> None:
        """Test case for put_services_bind_views_endpoint

        """
        pass

    def test_put_services_bind_zones_endpoint(self) -> None:
        """Test case for put_services_bind_zones_endpoint

        """
        pass

    def test_put_services_cron_jobs_endpoint(self) -> None:
        """Test case for put_services_cron_jobs_endpoint

        """
        pass

    def test_put_services_dhcp_servers_endpoint(self) -> None:
        """Test case for put_services_dhcp_servers_endpoint

        """
        pass

    def test_put_services_dns_forwarder_host_overrides_endpoint(self) -> None:
        """Test case for put_services_dns_forwarder_host_overrides_endpoint

        """
        pass

    def test_put_services_dns_resolver_access_lists_endpoint(self) -> None:
        """Test case for put_services_dns_resolver_access_lists_endpoint

        """
        pass

    def test_put_services_dns_resolver_domain_overrides_endpoint(self) -> None:
        """Test case for put_services_dns_resolver_domain_overrides_endpoint

        """
        pass

    def test_put_services_dns_resolver_host_overrides_endpoint(self) -> None:
        """Test case for put_services_dns_resolver_host_overrides_endpoint

        """
        pass

    def test_put_services_ha_proxy_backends_endpoint(self) -> None:
        """Test case for put_services_ha_proxy_backends_endpoint

        """
        pass

    def test_put_services_ha_proxy_files(self) -> None:
        """Test case for put_services_ha_proxy_files

        """
        pass

    def test_put_services_ha_proxy_frontends_endpoint(self) -> None:
        """Test case for put_services_ha_proxy_frontends_endpoint

        """
        pass

    def test_put_services_ntp_time_servers_endpoint(self) -> None:
        """Test case for put_services_ntp_time_servers_endpoint

        """
        pass

    def test_put_services_service_watchdogs_endpoint(self) -> None:
        """Test case for put_services_service_watchdogs_endpoint

        """
        pass


if __name__ == '__main__':
    unittest.main()
