# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfsense_api_client.models.patch_system_restapi_settings_endpoint_request import PatchSystemRESTAPISettingsEndpointRequest

class TestPatchSystemRESTAPISettingsEndpointRequest(unittest.TestCase):
    """PatchSystemRESTAPISettingsEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchSystemRESTAPISettingsEndpointRequest:
        """Test PatchSystemRESTAPISettingsEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchSystemRESTAPISettingsEndpointRequest`
        """
        model = PatchSystemRESTAPISettingsEndpointRequest()
        if include_optional:
            return PatchSystemRESTAPISettingsEndpointRequest(
                enabled = True,
                read_only = True,
                keep_backup = True,
                login_protection = True,
                log_successful_auth = True,
                allow_pre_releases = True,
                hateoas = True,
                expose_sensitive_fields = True,
                override_sensitive_fields = [
                    ''
                    ],
                allowed_interfaces = [
                    ''
                    ],
                represent_interfaces_as = 'descr',
                auth_methods = [
                    ''
                    ],
                jwt_exp = 300,
                ha_sync = True,
                ha_sync_validate_certs = True,
                ha_sync_hosts = [
                    ''
                    ],
                ha_sync_username = '',
                ha_sync_password = ''
            )
        else:
            return PatchSystemRESTAPISettingsEndpointRequest(
        )
        """

    def testPatchSystemRESTAPISettingsEndpointRequest(self):
        """Test PatchSystemRESTAPISettingsEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
