# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfsense_api_client.models.post_interface_lagg_endpoint_request import PostInterfaceLAGGEndpointRequest

class TestPostInterfaceLAGGEndpointRequest(unittest.TestCase):
    """PostInterfaceLAGGEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostInterfaceLAGGEndpointRequest:
        """Test PostInterfaceLAGGEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostInterfaceLAGGEndpointRequest`
        """
        model = PostInterfaceLAGGEndpointRequest()
        if include_optional:
            return PostInterfaceLAGGEndpointRequest(
                laggif = '',
                descr = '',
                members = [
                    ''
                    ],
                proto = 'lacp',
                lacptimeout = 'slow',
                lagghash = 'l2,l3,l4',
                failovermaster = 'auto'
            )
        else:
            return PostInterfaceLAGGEndpointRequest(
                members = [
                    ''
                    ],
                proto = 'lacp',
        )
        """

    def testPostInterfaceLAGGEndpointRequest(self):
        """Test PostInterfaceLAGGEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
