# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfsense_api_client.api.interface_api import INTERFACEApi


class TestINTERFACEApi(unittest.TestCase):
    """INTERFACEApi unit test stubs"""

    def setUp(self) -> None:
        self.api = INTERFACEApi()

    def tearDown(self) -> None:
        pass

    def test_delete_interface_bridge_endpoint(self) -> None:
        """Test case for delete_interface_bridge_endpoint

        """
        pass

    def test_delete_interface_gre_endpoint(self) -> None:
        """Test case for delete_interface_gre_endpoint

        """
        pass

    def test_delete_interface_gres_endpoint(self) -> None:
        """Test case for delete_interface_gres_endpoint

        """
        pass

    def test_delete_interface_group_endpoint(self) -> None:
        """Test case for delete_interface_group_endpoint

        """
        pass

    def test_delete_interface_groups_endpoint(self) -> None:
        """Test case for delete_interface_groups_endpoint

        """
        pass

    def test_delete_interface_lagg_endpoint(self) -> None:
        """Test case for delete_interface_lagg_endpoint

        """
        pass

    def test_delete_interface_laggs_endpoint(self) -> None:
        """Test case for delete_interface_laggs_endpoint

        """
        pass

    def test_delete_interface_vlan_endpoint(self) -> None:
        """Test case for delete_interface_vlan_endpoint

        """
        pass

    def test_delete_interface_vlans_endpoint(self) -> None:
        """Test case for delete_interface_vlans_endpoint

        """
        pass

    def test_delete_network_interface_endpoint(self) -> None:
        """Test case for delete_network_interface_endpoint

        """
        pass

    def test_delete_network_interfaces_endpoint(self) -> None:
        """Test case for delete_network_interfaces_endpoint

        """
        pass

    def test_get_interface_apply_endpoint(self) -> None:
        """Test case for get_interface_apply_endpoint

        """
        pass

    def test_get_interface_available_interfaces_endpoint(self) -> None:
        """Test case for get_interface_available_interfaces_endpoint

        """
        pass

    def test_get_interface_bridge_endpoint(self) -> None:
        """Test case for get_interface_bridge_endpoint

        """
        pass

    def test_get_interface_bridges_endpoint(self) -> None:
        """Test case for get_interface_bridges_endpoint

        """
        pass

    def test_get_interface_gre_endpoint(self) -> None:
        """Test case for get_interface_gre_endpoint

        """
        pass

    def test_get_interface_gres_endpoint(self) -> None:
        """Test case for get_interface_gres_endpoint

        """
        pass

    def test_get_interface_group_endpoint(self) -> None:
        """Test case for get_interface_group_endpoint

        """
        pass

    def test_get_interface_groups_endpoint(self) -> None:
        """Test case for get_interface_groups_endpoint

        """
        pass

    def test_get_interface_lagg_endpoint(self) -> None:
        """Test case for get_interface_lagg_endpoint

        """
        pass

    def test_get_interface_laggs_endpoint(self) -> None:
        """Test case for get_interface_laggs_endpoint

        """
        pass

    def test_get_interface_vlan_endpoint(self) -> None:
        """Test case for get_interface_vlan_endpoint

        """
        pass

    def test_get_interface_vlans_endpoint(self) -> None:
        """Test case for get_interface_vlans_endpoint

        """
        pass

    def test_get_network_interface_endpoint(self) -> None:
        """Test case for get_network_interface_endpoint

        """
        pass

    def test_get_network_interfaces_endpoint(self) -> None:
        """Test case for get_network_interfaces_endpoint

        """
        pass

    def test_patch_interface_bridge_endpoint(self) -> None:
        """Test case for patch_interface_bridge_endpoint

        """
        pass

    def test_patch_interface_gre_endpoint(self) -> None:
        """Test case for patch_interface_gre_endpoint

        """
        pass

    def test_patch_interface_group_endpoint(self) -> None:
        """Test case for patch_interface_group_endpoint

        """
        pass

    def test_patch_interface_lagg_endpoint(self) -> None:
        """Test case for patch_interface_lagg_endpoint

        """
        pass

    def test_patch_interface_vlan_endpoint(self) -> None:
        """Test case for patch_interface_vlan_endpoint

        """
        pass

    def test_patch_network_interface_endpoint(self) -> None:
        """Test case for patch_network_interface_endpoint

        """
        pass

    def test_post_interface_apply_endpoint(self) -> None:
        """Test case for post_interface_apply_endpoint

        """
        pass

    def test_post_interface_bridge_endpoint(self) -> None:
        """Test case for post_interface_bridge_endpoint

        """
        pass

    def test_post_interface_gre_endpoint(self) -> None:
        """Test case for post_interface_gre_endpoint

        """
        pass

    def test_post_interface_group_endpoint(self) -> None:
        """Test case for post_interface_group_endpoint

        """
        pass

    def test_post_interface_lagg_endpoint(self) -> None:
        """Test case for post_interface_lagg_endpoint

        """
        pass

    def test_post_interface_vlan_endpoint(self) -> None:
        """Test case for post_interface_vlan_endpoint

        """
        pass

    def test_post_network_interface_endpoint(self) -> None:
        """Test case for post_network_interface_endpoint

        """
        pass

    def test_put_interface_groups_endpoint(self) -> None:
        """Test case for put_interface_groups_endpoint

        """
        pass


if __name__ == '__main__':
    unittest.main()
