# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfsense_api_client.models.patch_vpni_psec_phase1_encryption_endpoint_request import PatchVPNIPsecPhase1EncryptionEndpointRequest

class TestPatchVPNIPsecPhase1EncryptionEndpointRequest(unittest.TestCase):
    """PatchVPNIPsecPhase1EncryptionEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchVPNIPsecPhase1EncryptionEndpointRequest:
        """Test PatchVPNIPsecPhase1EncryptionEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchVPNIPsecPhase1EncryptionEndpointRequest`
        """
        model = PatchVPNIPsecPhase1EncryptionEndpointRequest()
        if include_optional:
            return PatchVPNIPsecPhase1EncryptionEndpointRequest(
                encryption_algorithm_name = 'aes',
                encryption_algorithm_keylen = 0,
                hash_algorithm = 'sha1',
                dhgroup = 1,
                prf_algorithm = 'sha256',
                parent_id = 56,
                id = 56
            )
        else:
            return PatchVPNIPsecPhase1EncryptionEndpointRequest(
                parent_id = 56,
                id = 56,
        )
        """

    def testPatchVPNIPsecPhase1EncryptionEndpointRequest(self):
        """Test PatchVPNIPsecPhase1EncryptionEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
