# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfsense_api_client.models.get_services_ha_proxy_frontends_endpoint200_response import GetServicesHAProxyFrontendsEndpoint200Response

class TestGetServicesHAProxyFrontendsEndpoint200Response(unittest.TestCase):
    """GetServicesHAProxyFrontendsEndpoint200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetServicesHAProxyFrontendsEndpoint200Response:
        """Test GetServicesHAProxyFrontendsEndpoint200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetServicesHAProxyFrontendsEndpoint200Response`
        """
        model = GetServicesHAProxyFrontendsEndpoint200Response()
        if include_optional:
            return GetServicesHAProxyFrontendsEndpoint200Response(
                code = 56,
                status = 'ok',
                response_id = '',
                message = '',
                data = [
                    openapi_client.models.ha_proxy_frontend.HAProxyFrontend(
                        name = '01', 
                        descr = '', 
                        status = 'active', 
                        a_extaddr = [
                            null
                            ], 
                        max_connections = 0, 
                        type = 'http', 
                        ha_acls = [
                            null
                            ], 
                        a_actionitems = [
                            null
                            ], 
                        backend_serverpool = '', 
                        socket_stats = True, 
                        dontlognull = True, 
                        dontlog_normal = True, 
                        log_separate_errors = True, 
                        log_detailed = True, 
                        a_errorfiles = [
                            null
                            ], 
                        client_timeout = 0, 
                        forwardfor = True, 
                        httpclose = 'http-keep-alive', 
                        advanced_bind = '', 
                        advanced = '', 
                        ssloffloadcert = '', 
                        ha_certificates = [
                            null
                            ], )
                    ],
                links = openapi_client.models._links._links()
            )
        else:
            return GetServicesHAProxyFrontendsEndpoint200Response(
        )
        """

    def testGetServicesHAProxyFrontendsEndpoint200Response(self):
        """Test GetServicesHAProxyFrontendsEndpoint200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
