# coding: utf-8

"""
    pfSense REST API Documentation

    ### Getting Started<br>- [Authentication and Authorization](https://pfrest.org/AUTHENTICATION_AND_AUTHORIZATION/)<br>- [Working with Object IDs](https://pfrest.org/WORKING_WITH_OBJECT_IDS/)<br>- [Queries, Filters, and Sorting](https://pfrest.org/QUERIES_FILTERS_AND_SORTING/)<br>- [Common Control Parameters](https://pfrest.org/COMMON_CONTROL_PARAMETERS/)<br>- [Working with HATEOAS](https://pfrest.org/WORKING_WITH_HATEOAS/)<br>

    The version of the OpenAPI document: v2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfsense_api_client.models.post_system_certificate_authority_generate_endpoint_request import PostSystemCertificateAuthorityGenerateEndpointRequest

class TestPostSystemCertificateAuthorityGenerateEndpointRequest(unittest.TestCase):
    """PostSystemCertificateAuthorityGenerateEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSystemCertificateAuthorityGenerateEndpointRequest:
        """Test PostSystemCertificateAuthorityGenerateEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSystemCertificateAuthorityGenerateEndpointRequest`
        """
        model = PostSystemCertificateAuthorityGenerateEndpointRequest()
        if include_optional:
            return PostSystemCertificateAuthorityGenerateEndpointRequest(
                descr = '',
                refid = '67ed081a7d9ed',
                trust = True,
                randomserial = True,
                serial = 0,
                is_intermediate = True,
                caref = '',
                keytype = 'RSA',
                keylen = 1024,
                ecname = '',
                digest_alg = '',
                lifetime = 1,
                dn_commonname = 'internal-ca',
                dn_country = '',
                dn_state = '',
                dn_city = '',
                dn_organization = '',
                dn_organizationalunit = '',
                crt = '',
                prv = ''
            )
        else:
            return PostSystemCertificateAuthorityGenerateEndpointRequest(
                descr = '',
                caref = '',
                keytype = 'RSA',
                keylen = 1024,
                ecname = '',
                digest_alg = '',
        )
        """

    def testPostSystemCertificateAuthorityGenerateEndpointRequest(self):
        """Test PostSystemCertificateAuthorityGenerateEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
